#!/bin/bash

# dnsmasq
sudo systemctl stop dnsmasq
sudo systemctl disable dnsmasq

# nano
sudo nano /etc/dhcpcd.conf
sudo nano /etc/wpa_supplicant/wpa_supplicant.conf

# restart dncpcd

sudo systemctl restart dhcpcd

# upgrade apt
sudo apt-get update ; sudo apt-get upgrade

# install files for git
git clone https://github.com/CopterExpress/clever-show.git --branch python3
sudo pip3 install -r /home/pi/clever-show/drone/requirements.txt --upgrade

# chrony
sudo cp /home/pi/clever-show/examples/chrony/client.conf /etc/chrony/chrony.conf
sudo systemctl restart chrony

# copy files 
sudo cp /home/pi/clever-show/builder/assets/clever-show.service /lib/systemd/system
sudo systemctl enable clever-show.service
sudo systemctl start clever-show.service

sudo cp /home/pi/clever-show/builder/assets/failsafe.service /lib/systemd/system/
sudo systemctl enable failsafe.service
sudo systemctl start failsafe.service
