#!/bin/bash

# dnsmasq
sudo systemctl stop dnsmasq
sudo systemctl disable dnsmasq

# nano
sudo nano /etc/dhcpcd.conf
sudo nano /etc/wpa_supplicant/wpa_supplicant.conf

# restart dncpcd

sudo systemctl restart dhcpcd
